name: mal_api
description: A Dart wrapper for MyAnimeList REST API.
version: 1.0.2
homepage: https://gitlab.com/hingen/dart_mal_api

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  http: ^1.2.2
  oauth2: ^2.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
